#!/bin/sh

### BEGIN INIT INFO
# Provides:        ntp
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: Start NTP daemon
### END INIT INFO

NTPD_OPTS="-p /var/run/ntp.pid"

DAEMON=/usr/local/bin/ntpd
PIDFILE=/var/run/ntpd.pid

NTPD_OPTS="-p $PIDFILE"

case $1 in
	start)
		##log_daemon_msg "Starting NTP server" "ntpd"
		##if [ -z "$UGID" ]; then
		##	log_failure_msg "user \"$RUNASUSER\" does not exist"
		##	exit 1
		##fi
		start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- $NTPD_OPTS
		##log_end_msg $?
  		;;
	stop)
		##log_daemon_msg "Stopping NTP server" "ntpd"
		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE --retry=TERM/30/KILL/5 --exec $DAEMON
		##log_end_msg $?
		rm -f $PIDFILE
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		##status_of_proc $DAEMON "NTP server"
        status="0"
        pidof ntpd >/dev/null || status="$?"
        if [ "$status" = 0 ]; then
            echo "ntpd is running"
            exit 0
        else
            echo "ntpd is not running"
            exit $status
        fi
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
